
# production:
#   adapter: postgresql
#   database: sources_production
#   host: localhost
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  database: sources_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: sources_test
  host: localhost